@startuml
start
:Setup dataset;

if (Preprocessing only?) then (yes)
  if (Check accuracy?) then (yes)
    ->Original\nDatasets;
    :Train Models;
    ->Original\nModels;
    :Predict;
    ->Original\nPredictions;
  else (no)
  endif
else (Others\nCombinations) 
  ->Original\nDatasets;
  :Train Models;
  ->Original\nModels;
  :Predict;
  ->Original\nPredictions;
endif
:Measure Biases;
->Original Bias\nMeasurement Results;
(A)

detach
(A)
if (Preprocessing Mitigation?)
  -> Original\nDatasets;
  :Mitigate Bias;
  -> Mitigated\nOriginal\nDatasets;
else (no)
endif
if (Inprocessing Mitigation?) then (Yes)
  -> Original\nModels;
  :Mitigate Bias;
  -> Mitigated\nOriginal\nModels;
else (no)
endif
if (Postprocessing Mitigation?)
  -> Original\nPredictions;
  :Mitigate Bias;
  -> Mitigated\nOriginal\nPredictions;
else (no)
endif
(B)

detach
(B)
if (Preprocessing only?) then (yes)
  if (Check accuracy?) then (yes)
    -> Mitigated\nOriginal\nDatasets;
    :Train Models;
    -> Mitigated\nDataset\nModels;
    :Predict;
    -> Mitigated\nDataset\nModel\nPredictions;
  else (no)
  endif
else (no)
  
  if (Preprocessing mitigation?) then (yes)
    -> Mitigated\nOriginal\nDatasets;
    :Train Models;
    -> Mitigated\ndataset\nModels;
  else ((no)\nMitigated\nOriginal\nModels/\nOriginal\nModels) 
    
  endif

  if (Inprocessing mitigation?) then (yes)
      if (Preprocesing\nmitigation?) then (yes)
        -> Mitigated\nDateset\nModels;
        :Predict;
        -> Mitigated\nDataset\nModel\nPreditictons;
      endif 
      -> Mitigated\nOriginal\nModels;
      :Predict;
      -> Mitigated\nOriginal\nModels\nPredictions\n\n;
  else ((no)\nOriginal\nPredictions,\nMitigated\nOriginal\nPredictions) 
  endif 
endif
:Measure Biases;
->Mitigated Bias\nMeasurement Results;
stop
@enduml